name: contracts-appraisal-v2

on:
  push:
    branches:
      - main

env:
  SERVICE_FOLDER: .
  NODEJS_VERSION: 14.x

jobs:
  deploy-test:
    name: ContractsAppraisal
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: us-east-1
      PROD_ACCOUNT_ID: ${{ secrets.PROD_ACCOUNT_ID }}
      APP_API_ACCESS_KEY: ${{ secrets.APP_API_ACCESS_KEY }}
      SCHEDULER_URL: ${{ secrets.SCHEDULER_URL }}
      SCHEDULER_USER: ${{ secrets.SCHEDULER_USER }}
      SCHEDULER_API_KEY: ${{ secrets.SCHEDULER_API_KEY }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODEJS_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODEJS_VERSION }}

      # Other steps here include npm install, linting, unit tests, etc
      # Run npm install to get dependencies and make sls available on the path
      - run: npm install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Post-deployment test steps go here
      - name: 'Deploying to stage: prod'
        uses: './.github/actions/sls-deploy'
        with:
          service-folder: ${{ env.SERVICE_FOLDER }}
          stage: prod
          aws-account-id: ${{ env.PROD_ACCOUNT_ID }}
          app-api-access-key: ${{ env.APP_API_ACCESS_KEY }}
          scheduler-url: ${{ env.SCHEDULER_URL }}
          scheduler-user: ${{ env.SCHEDULER_USER }}
          scheduler-api-key: ${{ env.SCHEDULER_API_KEY }}
      # Post-deployment test steps go here